version: "3.7"

services:
  it-marathon-mongo:
    image: mongo:latest
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - ./mongo_volume:/data/db

  it-marathon-mysql:
    image: mysql:latest
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql_volume:/var/lib/mysql
      - ./scripts/:/docker-entrypoint-initdb.d/ # nu merge aparent....

